GroupManage/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from qlnhom.models import MonHoc

admin.autodiscover()

dsmon_lookup = {
    'queryset': MonHoc.objects.all(),
    'field': 'ten_mon',  # this is the field which is searched
    'field_extract': ['gioi_thieu', 'nam_hoc'],
    #'limit': 10, # default is to limit query to 10 results. Increase this if you like.
    #'login_required': onhocFalse, # default is to allow anonymous queries. Set to True if you want authenticated access.
}

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'GroupManage.views.home', name='home'),
                       # url(r'^GroupManage/', include('GroupManage.foo.urls')),

                       # Uncomment the admin/doc line below to enable admin documentation:
                       #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

                       # Uncomment the next line to enable the admin:

                       url(r'^admin/', include(admin.site.urls)),
                       (r'^accounts/', include('userena.urls')),
                       (r'^grappelli/', include('grappelli.urls')),


) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += patterns('qlnhom.views',
                        url(r'^$', 'index', name='home_page'),
                        url(r'^monhoc/dsmon_lookup$', 'json_lookup', dsmon_lookup, name="dsmon_lookup"),
                        url(r'^monhoc/dsnhom_lookup$', 'listgroup', name='dsnhom'),
                        url(r'^monhoc/taonhom$', 'taonhom', name='taonhom'),
                        url(r'^monhoc/(?P<monhoc>.+)-(?P<monhocid>\d+)$', 'monhoc', name='monhoc'),
                        url(r'^monhoc/(?P<monhoc>.+)-(?P<monhocid>\d+)/taonhom$', 'taonhom', name='taonhommonhoc'),
                        url(r'^(?P<username>.*)/dsnhom/$', 'dsnhomjoined', name="dsnhomjoined"),
                        url(r'^(?P<monhoc>.+)-(?P<monhocid>\d+)/(?P<nhom>.+)-(?P<nhomid>\d+)$', 'nhom', name="nhom"),
                        url(r'^(?P<monhoc>.+)-(?P<monhocid>\d+)/(?P<nhom>.+)-(?P<nhomid>\d+)/join$', 'jointogroup',
                                                                                                name="jointogroup"),
                        url(r'^(?P<monhoc>.+)-(?P<monhocid>\d+)/(?P<nhom>.+)-(?P<nhomid>\d+)/out$', 'outgroup',
                            name="outgroup"),
                        url(r'^(?P<monhoc>.+)-(?P<monhocid>\d+)/(?P<nhom>.+)-(?P<nhomid>\d+)/delete$', 'deletegroup',),
)
urlpatterns += patterns('thaoluan.views',
                        url(r'^(?P<monhoc>.+)-(?P<monhocid>\d+)/'
                            r'(?P<nhom>.+)-(?P<nhomid>\d+)/thaoluan$', 'thaoluannhom') ,
                        url(r'^(?P<monhoc>.+)-(?P<monhocid>\d+)/'
                            r'(?P<nhom>.+)-(?P<nhomid>\d+)/thaoluan/(?P<thaoluanid>.+)$', 'thaoluanchitiet'),
                        )

qlnhom/urls.py
__author__ = 'nampnq'

qlnhom/models.py
# encoding: utf-8

from django.db import models
from django.contrib.auth.models import User
import datetime
from unidecode import unidecode
from django.template.defaultfilters import slugify
from django.conf import settings

YEAR_CHOICES = []
for i in range(2000, datetime.datetime.now().year + 1):
    YEAR_CHOICES.append((i, i))

Loai_Nhom_Choice = (
    (0, 'Public'),
    (1, 'Private'),
)


class MonHoc(models.Model):
    ten_mon = models.CharField('Tên môn học', max_length=50)
    gioi_thieu = models.CharField('Giới thiệu về nhóm', max_length=500)
    nam_hoc = models.IntegerField('Năm học', max_length=4, choices=YEAR_CHOICES, default=datetime.datetime.now().year)

    def __unicode__(self):
        return self.ten_mon

    @models.permalink
    def get_absolute_url(self):
        return ('monhoc', (), {
            'monhoc': slugify(unicode(unidecode(self.ten_mon))),
            'monhocid': self.pk,
        })

    class Meta:
        verbose_name = "Môn học"
        verbose_name_plural = "Danh sách môn học"

MAX_SL_CHOICES = zip(range(1, settings.NAMPNQ_GM_MAX_MEMBER_COUNT + 1), range(1, settings.NAMPNQ_GM_MAX_MEMBER_COUNT + 1))


class Nhom(models.Model):
    ten_nhom = models.CharField('Tên nhóm', max_length=50)
    mon_hoc = models.ForeignKey('MonHoc', verbose_name='Tên Môn Học')
    max_sl = models.SmallIntegerField("Số lượng", choices=MAX_SL_CHOICES, default=1)
    gioi_thieu_nhom = models.CharField('Giới thiệu về nhóm', max_length=500)
    loai_nhom = models.SmallIntegerField('Loại nhóm', choices=Loai_Nhom_Choice, default=0)
    dsthanhvien = models.ManyToManyField(User, through='ThanhVienNhom', verbose_name='Danh sách thành viên')

    def is_full_member(self):
        return self.dsthanhvien.count() >= self.max_sl

    def __unicode__(self):
        return self.ten_nhom

    class Meta:
        verbose_name = "Nhóm"
        verbose_name_plural = "Danh sách nhóm"

    @models.permalink
    def get_absolute_url(self):
        return('nhom', (), {
            'monhoc': slugify(unicode(unidecode(self.mon_hoc.ten_mon))),
            'monhocid': self.mon_hoc_id,
            'nhom': slugify(unicode(unidecode(self.ten_nhom))),
            'nhomid': self.pk,
        })


class ThanhVienNhom(models.Model):
    user = models.ForeignKey(User, verbose_name='Tên thành viên')
    nhom = models.ForeignKey('Nhom', verbose_name='Nhóm tham gia')
    ngay_tham_gia = models.DateField(auto_now_add=True)
    acitve = models.BooleanField('Kích hoạt', default=not settings.NAMPNQ_GM_REQUIRED_ACTIVE)
    nhom_truong = models.BooleanField('Nhóm trưởng', default=False)

    class Meta:
        verbose_name = "Thành viên"
        verbose_name_plural = "Danh sách thành viên"
        unique_together = ('user', 'nhom')

    def __unicode__(self):
        return self.user.username

    def clean(self):
        from django.core.exceptions import ValidationError

        if self.user.nhom_set.all().filter(mon_hoc_id=self.nhom.mon_hoc):
            raise ValidationError(u"Môn học %s bạn %s đã có nhóm" % (self.nhom.mon_hoc, self.user))
        if self.nhom.is_full_member():
            raise ValidationError(u"Nhóm này đã full rồi")

thaoluan/models.py
# encoding: utf8
from django.db import models
from django.contrib.auth.models import User
from qlnhom.models import Nhom


class ChuDe(models.Model):
    tieu_de = models.CharField('Tiêu đề', max_length=500)
    ngay_tao = models.DateTimeField('Ngày tạo', auto_now_add=True)
    nguoi_tao = models.ForeignKey(User, verbose_name='Người tạo')
    nhom = models.ForeignKey(Nhom, verbose_name='Nhóm')
    noi_dung = models.TextField('Nội dung')

    class Meta:
        verbose_name_plural = "Danh sách chủ đề"
        verbose_name = "Chủ đề"
        ordering = ['-ngay_tao']

    def __unicode__(self):
        return u"Thảo luận #%d - Nhóm %s" % (self.pk, self.nhom)


class BinhLuan(models.Model):
    chu_de = models.ForeignKey('ChuDe', verbose_name='Chủ đề')
    nguoi_gui = models.ForeignKey(User, verbose_name='Người gửi')
    ngay_gui = models.DateTimeField('Ngày gửi', auto_now_add=True)
    noi_dung = models.CharField('Nội dung', max_length=500)

    class Meta:
        verbose_name_plural = "Danh sách bình luận"
        verbose_name = "Bình luận"
        ordering = ['ngay_gui']

    def __unicode__(self):
        return u"Bình luận #%d - Chủ đề #%d" % (self.pk, self.chu_de_id)

templates/_corfirmOut.html
<p>Bạn {{ user.username }} thực sự muốn rời khỏi nhóm {{ nhom.ten_nhom }}</p>
<form method="POST" action="{{ get_full_path }}">
    {% csrf_token %}
</form>

templates/_ds_nhom_ajax.html
{% load isNhomTruong %}
{% if nhoms %}
{% for nhom in nhoms %}
<tr class="{% if nhom.is_full_member %}error{% else %}info{% endif %}">
    <td>
        {% if nhom.is_full_member %}
            <span class="label label-warning">FULL</span>
        {% endif %}
        <div>
            <b>{{ nhom.ten_nhom }}</b><br>
            <em>{{ nhom.gioi_thieu_nhom }}</em><br>
            <b><span style="text-decoration: underline;">Thành viên:</span> </b>
            {% if nhom.dsthanhvien.count <= 0 %}(Chưa có thành viên){% endif %}
            {% for m in nhom.thanhviennhom_set.all %}
                <span class="label {% if m.nhom_truong %}label-important{% elif not m.acitve %}label-warning{% else %}label-info{% endif %}">{{ m.user }}</span> {% if not forloop.last %},{% endif %}
            {% endfor %}
        </div>
    </td>

    <td>
        <div class="btn-toolbar pull-right">
            <div class="btn-group">
            {% if user in nhom.dsthanhvien.all %}
                <a href="{{ nhom.get_absolute_url }}/out" class="btn btn-warning ajax-modal" data-target = "#outModal" data-method="post" data-replace-inner="#message" data-refresh="#dsnhom"><i class="icon-remove"></i> Bỏ nhóm</a>
                {% else %}
                    {% if not nhom.is_full_member %}
                        <a href="{{ nhom.get_absolute_url }}/join" class="btn btn-info ajax" data-method="get" data-replace-inner="#message" data-refresh="#dsnhom"><i class="icon-plus"></i> Tham gia</a>
                    {% endif %}
            {% endif %}
            {% if user.is_staff or user.pk|isNhomTruong:nhom.pk %}
                <a href="{{ nhom.get_absolute_url }}/delete" class="btn btn-danger ajax-modal" data-target = "#deleteModal" data-method="post" data-replace-inner="#message" data-refresh="#dsnhom"><i class="icon-trash"></i> Xóa</a>
            {% endif %}
            </div>
        </div>
    </td>
</tr>
{% if forloop.last %}
    <script>
        $("#newgroupBtn").attr("href","{{ nhom.mon_hoc.get_absolute_url }}/taonhom");
        $("#newgroupBtn").attr("data-modal","{{ nhom.mon_hoc.get_absolute_url }}/taonhom");
        $("#message").html("<div class='alert'><button type='button' class='close' data-dismiss='alert'>&times;</button>" +
                "<strong>Chú thích: </strong>  " +
                "<span class=\"label label-important\">Nhóm trưởng</span>  " +
                "<span class=\"label label-warning\">Thành viên chưa được xác nhận</span>  " +
                "<span class=\"label label-info\">Thành viên chính thức</span></div>");
    </script>
{% endif %}
{% endfor %}
{% else %}
<tr class="error">
        <td>
            <b>Hiện tại môn học này chưa có nhóm, bạn có thể bắt đầu tạo nhóm</b>
        </td>
</tr>
{% endif %}

templates/_dsnhom.html
<ul id="dsnhom" class="nav nav-list" data-refresh-url="{% url dsnhomjoined user %}">
    <li class="nav-header">Danh sách nhóm</li>
    {% if user.nhom_set.count <= 0 %}
        <b>Bạn chưa có nhóm!</b>
    {% else %}
        {% for group in user.nhom_set.all %}
            <li><a href="{{ group.get_absolute_url }}" class="ajax" data-replace-inner="#mainContent"><b>{{ group.mon_hoc }}</b><br><em>{{ group.ten_nhom }}</em></a></li>
        {% endfor %}
    {% endif %}
</ul>

templates/_nhom_binh_chon.html
Hiện chưa có bình chọn

templates/_nhom_detail.html
{% load isNhomTruong %}
<h5>Hệ thống quản lí nhóm</h5>
<hr>
<div class="well">
<b>{{ nhom.ten_nhom }} - Group Management</b>
<dl class="dl-horizontal">
        <dt>Môn học:</dt>
        <dd>{{ nhom.mon_hoc }}</dd>
        <dt>Giới thiệu:</dt>
        <dd>{{ nhom.gioi_thieu_nhom }}</dd>
</dl>
<b><span style="text-decoration: underline;">Thành viên:</span> </b>
{% if nhom.dsthanhvien.count <= 0 %}(Chưa có thành viên){% endif %}
{% for m in nhom.thanhviennhom_set.all %}
    <span class="label label-inverse">{{ m.user }}</span> {% if not forloop.last %},{% endif %}
{% endfor %}
</div>
<ul class="nav nav-tabs" id="nhomTab">
    <li><a href="#thaoluan" data-toggle="tab">Thảo Luận</a></li>
    <li><a href="#phancong" data-toggle="tab">Phân Công Nhóm</a></li>
    <li><a href="#binhchon" data-toggle="tab">Bình Chọn</a></li>
    {% if user.pk|isNhomTruong:nhom.pk %}
    <li><a href="#quanli" data-toggle="tab">Quản Lí Nhóm</a></li>
    {% endif %}
</ul>
<div class="tab-content">
    <div class="tab-pane" id="thaoluan" data-href="{{ nhom.get_absolute_url }}/thaoluan"></div>
    <div class="tab-pane" id="phancong" data-href="{{ nhom.get_absolute_url }}/phancong"></div>
    <div class="tab-pane" id="binhchon" data-href="{{ nhom.get_absolute_url }}/binhchon"></div>
    {% if user.pk|isNhomTruong:nhom.pk %}
    <div class="tab-pane" id="quanli">{% include '_nhom_quan_li.html' %}</div>
    {% endif %}
</div>
<script>
    $('a[data-toggle="tab"]').on('show', function (e) {
        var $a = $($(e.target).attr('href'));
        if($a.attr('data-href'))
        {
            $.getJSON($a.attr('data-href'), function(data)
            {
                $a.html(data.html);
            })
        }
    });
    $('a[href="#thaoluan"]').tab('show');
</script>

templates/_nhom_phan_cong.html
Hiện chưa có phân công

templates/_nhom_quan_li.html
Chức năng đang bảo trì

templates/_nhom_thao_luan.html
{% load humanize %}
{% if nhom.chude_set.all %}
<div class="accordion" id="thaoluan">
    <div class="accordion-group">
            {% for t in nhom.chude_set.all %}
                <div class="accordion-heading">
                    <div class="accordion-toggle" data-toggle="collapse" data-parent="#thaoluan" href="#chude{{ t.pk }}">
                        <p></p>
                        <div style="clear:both;padding-bottom:5px;">
                            <div style="float:left;width:250px;"><i class="icon-user"></i> <a href>{{ t.nguoi_tao }}</a>
                            </div>
                            <div style="float:left;width:250px;"><i class="icon-comment"></i> {{ t.binhluan_set.count }} Bình luận
                            </div>
                            <div style="float:left;"><i class="icon-time"></i> {{ t.ngay_tao|naturaltime }}
                            </div>
                        </div>
                        <br>
                        <div><a><b>{{ t.tieu_de }}</b></a></div>
                    </div>
                </div>
                <div id="chude{{ t.pk }}" class="accordion-body collapse" data-href="{{ nhom.get_absolute_url }}/thaoluan/{{ t.pk }}">

                </div>
                {% if not forloop.last %}<hr>{% endif %}
            {% endfor %}
    </div>
</div>
<script>
    $('.collapse').on('show', function () {
        var $this = $(this);
        if($this.attr('data-href'))
        {
            $this.html($.getJSON($this.attr('data-href'),function(data){
                $this.html(data.html);
                $this.removeAttr('style');
            }));
        }
    })
</script>
{% else %}
    <div class="well">
        Chưa có chủ đề
    </div>
{% endif %}
<div>
    <a href="#" class="btn btn-success"><i class="icon-pencil"></i> Đăng chủ đề</a>
</div>

templates/_taonhom.html
{% load bootstrap %}
{% if message %}
    <script id="mesScript">
        var $a = $("#mesScript").parent().parent();
        $($a).modal('hide');
        $($a.attr('data-replace-inner')).html("{{ message|safe }}");
        $.each($($a.attr('data-refresh')), function(index, value) {
            $.getJSON($(value).data('refresh-url'), function(data) {
                $(value).replaceWith(data.html)
            })
        })
    </script>
{% else %}
<form id="taonhom">
{% csrf_token %}
{{ form|bootstrap }}
</form>
{% endif %}

templates/_timkiemnhom.html
{% load compress %}
<h5>Hệ thống quản lí nhóm</h5>
<hr>
<h6>Tìm kiếm, tạo nhóm</h6>
<p>Danh sách các môn học</p>
<form class="form-inline ajax" method="post" action="{% url dsnhom %}" data-replace-inner="#result">
    {% csrf_token %}
    <input type="hidden" class="bigdrop" id="monhocid" name="id" style="width:600px">
    <input type="submit" class="btn" value="Tìm kiếm nhóm">
</form>
<div id="loading"></div>
<div id="message"></div>
<table class="table table-hover">
    <tbody id="result">

    </tbody>
</table>
<!-- Modal Corfirm Out  -->
<div id="outModal" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3>Xác nhận rời khỏi nhóm</h3>
    </div>
    <div class="modal-body">
        <p>Bạn chắc chắn muốn rời khỏi nhóm này?</p>
    </div>
    <div class="modal-footer">
        <button class="btn btn-danger corfirm">Uh,Chắc chắn</button>
        <button class="btn btn-secondary" data-dismiss="modal" aria-hidden="true">Không</button>
    </div>
</div>
<!-- Modal delete group  -->
<div id="deleteModal" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3>Xác nhận xóa nhóm</h3>
    </div>
    <div class="modal-body">
        <p>Bạn chắc chắn muốn xóa nhóm này?</p>
    </div>
    <div class="modal-footer">
        <button id="confirm" class="btn btn-danger corfirm">Uh,Chắc chắn</button>
        <button id="cancel" class="btn btn-secondary" data-dismiss="modal" aria-hidden="true">Không</button>
    </div>
</div>
<!-- Modal create group  -->
<div id="createGroup" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3>Tạo nhóm mới</h3>
    </div>
    <div class="modal-body">
        <p>Loading data...</p>
    </div>
    <div class="modal-footer">
        <button class="btn btn-danger submit">Xác nhận</button>
        <button class="btn btn-secondary" data-dismiss="modal" aria-hidden="true">Hủy</button>
    </div>
</div>
<a class="btn btn-success ajax-modal" data-modal="{% url taonhom %}" data-method="POST" data-target="#createGroup" data-refresh="#dsnhom" data-replace-inner="#message" id="newgroupBtn" href="{% url taonhom %}"><i class="icon-pencil"></i> Tạo nhóm mới</a>
{% compress 'js' %}
    <script type="text/javascript">
        $(document).ready(function() {
            $("#monhocid").select2({
                placeholder: "Nhập vào tên môn học cần tìm nhóm",
                minimumInputLength: 1,
                ajax: { // instead of writing the function to execute the request we use Select2's convenient helper
                    url: "{% url dsmon_lookup %}",
                    dataType: 'jsonp',
                    data: function (term) {
                        return {
                            q: term // search term
                        };
                    },
                    results: function (data) {
                        return {results: data.data};
                    }
                },
                formatResult: function (m) { return "<b>" + m.ten_mon + "</b><br><em>"+m.gioi_thieu +"</em><br><b>Năm học:</b>"+ m.nam_hoc; } , // omitted for brevity, see the source of this page
                formatSelection: function (m) { return m.ten_mon; } , // omitted for brevity, see the source of this page
                dropdownCssClass: "bigdrop", // apply css that makes the dropdown taller
                escapeMarkup: function (m) { return m; } // we do not want to escape markup since we are displaying html in results
            });
        });
        //Ajax Modal
        $(document).on('click','.modal-footer > button.corfirm',function(e){
            var $a = $(this).parent().parent();
            $a.modal('hide');
            $.ajax({
                url: $a.attr('href'),
                data: {
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                dataType:'json',
                type : $a.attr('data-method'),
                success:function(result){
                    $($a.attr('data-replace-inner')).html(result.html);
                    $.each($($a.attr('data-refresh')), function(index, value) {
                        $.getJSON($(value).data('refresh-url'), function(data) {
                            $(value).replaceWith(data.html)
                        })
                    });
                    $('html, body').animate({
                        scrollTop: $("#message").offset().top-60
                    }, 20);
                }});
        });
        //Ajax Modal Form
        $(document).on('click','.modal-footer > button.submit',function(e){
            var $a = $(this).parent().parent();
            //$a.modal('hide');
            $.ajax({
                url: $a.attr('href'),
                data:$($a.find('form')[0]).serialize(),
                dataType:'json',
                type : $a.attr('data-method'),
                success:function(result){
                    $a.find('.modal-body').html(result.html);
                }});
        });
        //Button click
        $(document).on('click', 'a.ajax-modal', function (e) {
            e.preventDefault();
            var $a = $(this);
            var $b = $($a.attr('data-target'));
            var attributes = $a.prop("attributes");
            $b.modal("show");
            $.each(attributes, function() {
                if(this.name !== "class" && this.name !== "data-target" && this.name !== "data-modal" && this.name !== "id" && this.name !== "name")
                    $b.attr(this.name, this.value);
            });
            if($a.attr('data-modal'))
            {
                $.getJSON($a.attr('data-modal'),function(data){
                    $($b).find('.modal-body').html(data.html)
                })
            }
            return false;
        });
</script>
{% endcompress %}

templates/base.html
{% load compress %}
<!-- skeleton code for using bootstrap in html -->
<!DOCTYPE html>
{% load static from staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="nampnq">
    {% block meta %}{% endblock %}

    <title> {% block title %} {% endblock title %} | NamPNQ Groups Management </title>

    {% compress css %}
    <!-- Le styles de bootstrap -->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" type="text/css" />
    <link rel="stylesheet" href="{% static "css/bootstrap-responsive.min.css" %}" type="text/css" />
    {% endcompress %}
    <!-- Google Font Lib -->
    <link href='http://fonts.googleapis.com/css?family=Dancing+Script:700,400' rel='stylesheet' type='text/css'>

    <!-- Your own css file -->
    <style type="text/css">{% block css %} {% endblock css %}</style>

    <!-- js files -->
    <script src="{% static "js/jquery.min.js" %}"></script>

    {% block csslink %} {% endblock csslink %}
    {% block js-head %} {% endblock js-head %}
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="{% static 'ico/favicon.ico' %}" />
    {% block icon %} {% endblock icon %}
  </head>

  <body style="min-width:995px;">
    {% block navbar %}{% endblock %}
    <div class="container-fluid">

        <h1>{% block content_title %}{% endblock %}</h1>
        {% block content %}{% endblock %}
        <hr>

        <footer>
            <p>&copy; <a herf="http://nampnq.info" title="Phạm Ngọc Quang Nam">NamPNQ Product</a> 2013</p>
        </footer>

    </div>
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/jquery.tinyscrollbar.min.js" %}"></script>
    {% block js %}{% endblock %}
  </body>
</html>

templates/index.html
{% extends "nav.html" %}
{% load static from staticfiles %}
{% load url from future %}

{% load thumbnail %}
{% load compress %}

{% block css %}
    {{ block.super }}
    .select2-highlighted .movie-synopsis {
    color: #EEEEEE;
    font-size: 0.8em;
    }
    .bigdrop.select2-container .select2-results {
    max-height: 300px;
    }
    .bigdrop .select2-results {
    max-height: 300px;
    }
{% endblock %}

{% block csslink %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/select2.css' %}" type="text/css" />
{% endblock %}

{% block title %}
    Welcome
{% endblock %}
{% block content %}
    <div class="row-fluid">
        <div class="span3">
            <div class="well sidebar-nav">
                {% include "_dsnhom.html" %}
            </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
           <div id="mainContent" class="span12 well">
                {% include "_timkiemnhom.html" %}
           </div>
        </div><!--/span-->
    </div><!--/row-->
{% endblock %}
{% block js-head %}
    <script type="text/javascript" src="{% static "js/select2.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/bootstrap-ajax.js"  %}"></script>
{% endblock %}
{% block js %}
{% endblock %}

templates/terms_of_service.html
<p>By clicking the button, you agree to the terms below:</p>
<p>By using and accessing this website, http://cmpt470.csil.sfu.ca:8014 (collectively referred to as the "Site" or "Chief" in these Terms of Service), you ("you", "user" or, "end user") agree to these Terms of Service (collectively, the "Terms of Service" or "Agreement").</p>

<p>IF YOU DO NOT AGREE TO THE TERMS OF THIS AGREEMENT, IMMEDIATELY STOP ACCESSING THIS SITE.</p>

<p>You agree not to modify, copy, distribute, transmit, display, perform, reproduce, publish, license, transfer, create derivate work from, sell or re-sell any content or information obtained from or through the Site.</p>

<p><strong>Third-party Sites.</strong><br />The Site may contain links to other websites maintained by third-parties. These links are provided solely as a convenience and does not imply endorsement of, or association with, the party by Chief.</p>

<p><strong>Modifications to this Agreement.</strong><br />Chief reserves the right to change or modify any of the terms and conditions contained in this Agreement at any time. You acknowledge and agree that it is your responsibility to review the Site and these Terms of Service from time to time. Your continued use of the Site after such modifications to this Agreement will constitute acknowledgment of the modified Terms of Service and agreement to abide and be bound by the modified Terms of Service.</p>

<p><strong>Termination of Use.</strong><br />Chief shall have the right to immediately terminate or suspend, in its discretion, your access to all or part of the Site with or without notice for any reason.</p>

<p><strong>Limitation of Liability.</strong><br />In no event shall Chief or its affiliates be liable for any indirect, incidental, special, punitive damages or consequential damages of any kind, or any damages whatsoever arising out of or related to your use of the Site, the content and other information obtained therein.</p>

<p>Certain jurisdictions prohibit the exclusion or limitation of liability for consequential or incidental damages, thus the above limitations may not apply to you. </p>

<p><strong>Governing Law.</strong><br />Any disputes arising out of or related to these Terms of Service and/or any use by you of the Site shall be governed by the laws of the Canada, without regard to the conflicts of laws provisions therein.</p>

<p><strong>Date of Last Update.</strong><br />This agreement was last updated on October 31, 2012.</p>

<p>Published with permission from <a href="http://termsfeed.com" title="Termsfeed">Termsfeed</a>.</p>

<style>
    div.overview p {
        margin-left: 0;
        padding-left: 0;
    }
</style>